version: "3"
services:

  eureka-service:
    container_name: eureka-discovery
    image: eureka-service
    ports:
      - "8761:8761"

  config-service:
    container_name: configuration
    image: config-service
    environment:
      GITHUB_USER: yofujitsu
      GITHUB_TOKEN: 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
      GITHUB_URL: https://github.com/rksp8/config.git

    ports:
      - "8888:8888"

  postgresql:
    container_name: postgresql_rksp8
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rksp8
      PGDATA: /data/rksp8
    volumes:
      - postgres:/data/rksp8
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: