apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: yofujitsu/config-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: GITHUB_USERNAME
              value: yofujitsu
            - name: GITHUB_TOKEN
              value: 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
            - name: GITHUB_URL
              value: https://github.com/rksp8/config.git
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30888
  type: NodePort